### ISSUE TITLE
contributor graph not working

### ISSUE THREAD

**Issue by merlinseela** [mezotv/awesome-gamedev#40]
Contributors
Shout out to the awesome people who contributed to this awesome list!

some graph

@mezotv

**Comment by mezotv** [comment]
Not sure what you mean with this?

**Comment by merlinseela** [comment]
at the bottom of the list there is a contributors section.

now it renders something when i opened the issue it did not.

anyway but now this is somehwat redundant with the authors section at the beginning of the list.

i think we should only keep one of them.

**Comment by mezotv** [comment]
> at the bottom of the list there is a contributors section.
> 
> now it renders something when i opened the issue it did not.
> 
> anyway but now this is somehwat redundant with the authors section at the beginning of the list.
> 
> i think we should only keep one of them.

We should keep both cause its different things.
